version: '3'

services:
  database:
    image: mysql:latest
    restart: always
    container_name: bdd-tradeinluxe
    environment:
      MYSQL_DATABASE: tradeinluxedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

volumes:
  database_data:
